[package]
name = "gpu-funs"
version = "0.1.0"
edition = "2024"

[dependencies]
generic-array = "1.2.0"
image = "0.25.6"
obj = "0.10.2"
rand = "0.9.2"
rayon = "1.11.0"
typenum = { version = "1.18.0", features = ["const-generics"] }
